name: Compilar Kernel OP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar y Compilar
        uses: utsavbalaji/Kernel-Action-Mmp@master
        with:
          kernel-url: https://github.com/DevZillion/android_kernel_samsung_gta7litewifixx
          kernel-dir: mmp
          kernel-branch: master
          config: gta7lite_eur_open_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          
